// clients/vue-client/src/components/ProductForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useProducts } from '../composables/useProducts';

const { createProduct, isCreating } = useProducts();

const name = ref('');
const description = ref('');
const price = ref('');
const stock = ref('');
const message = ref('');
const error = ref('');

const handleSubmit = async () => {
  message.value = '';
  error.value = '';

  const result = await createProduct({
    name: name.value,
    description: description.value || null,
    price: Number(price.value),
    stock: Number(stock.value),
  });

  if (result.success) {
    message.value = 'Producto creado exitosamente';
    // Reset form
    name.value = '';
    description.value = '';
    price.value = '';
    stock.value = '';
  } else {
    error.value = result.error || 'Failed to create product';
  }
};
</script>

<template>
  <form class="product-form" @submit.prevent="handleSubmit" data-testid="product-form">
    <h2>Crear Producto</h2>

    <div class="form-group">
      <input
        v-model="name"
        type="text"
        placeholder="Nombre del producto"
        required
        data-testid="product-name"
      />
    </div>

    <div class="form-group">
      <input
        v-model="description"
        type="text"
        placeholder="Descripción (opcional)"
        data-testid="product-description"
      />
    </div>

    <div class="form-row">
      <div class="form-group">
        <input
          v-model="price"
          type="number"
          step="0.01"
          min="0"
          placeholder="Precio"
          required
          data-testid="product-price"
        />
      </div>

      <div class="form-group">
        <input
          v-model="stock"
          type="number"
          min="0"
          placeholder="Stock"
          required
          data-testid="product-stock"
        />
      </div>
    </div>

    <button 
      type="submit" 
      :disabled="isCreating"
      data-testid="create-button"
    >
      {{ isCreating ? 'Creando...' : 'Crear Producto' }}
    </button>

    <p v-if="message" class="success" data-testid="success-message">
      {{ message }}
    </p>

    <p v-if="error" class="error" data-testid="error-message">
      {{ error }}
    </p>
  </form>
</template>

<style scoped>
.product-form {
  background: #111827;
  border: 1px solid #334155;
  border-radius: 16px;
  padding: 24px;
  margin-bottom: 24px;
}

.product-form h2 {
  margin-top: 0;
  margin-bottom: 20px;
  color: #e2e8f0;
}

.form-group {
  margin-bottom: 16px;
}

.form-row {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
}

input {
  width: 100%;
  padding: 12px;
  border-radius: 10px;
  border: 1px solid #475569;
  background: #0f172a;
  color: white;
  font-size: 14px;
}

input:focus {
  outline: none;
  border-color: #3b82f6;
}

button {
  width: 100%;
  padding: 12px;
  border: none;
  border-radius: 10px;
  background: #10b981;
  color: white;
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.2s;
}

button:hover:not(:disabled) {
  background: #059669;
}

button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.success {
  margin-top: 12px;
  color: #10b981;
  font-size: 14px;
}

.error {
  margin-top: 12px;
  color: #ef4444;
  font-size: 14px;
}
</style>

// clients/react-client/src/components/ProductForm.jsx
/**
 * ProductForm Component
 * Form for creating new products
 */

import { useState } from 'react';
import './ProductForm.css';

const initialFormState = {
  name: '',
  description: '',
  price: '',
  stock: '',
};

export function ProductForm({ onSubmit, loading }) {
  const [formData, setFormData] = useState(initialFormState);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    const productData = {
      name: formData.name,
      description: formData.description || null,
      price: parseFloat(formData.price),
      stock: parseInt(formData.stock, 10),
    };

    const result = await onSubmit(productData);
    
    if (result.success) {
      setFormData(initialFormState);
    }
  };

  return (
    <form className="product-form" onSubmit={handleSubmit} data-testid="product-form">
      <h2>Crear Producto</h2>

      <div className="form-row">
        <div className="form-group">
          <label htmlFor="name">Nombre *</label>
          <input
            id="name"
            name="name"
            type="text"
            value={formData.name}
            onChange={handleChange}
            placeholder="Nombre del producto"
            required
            disabled={loading}
            data-testid="product-name-input"
          />
        </div>

        <div className="form-group">
          <label htmlFor="description">Descripción</label>
          <input
            id="description"
            name="description"
            type="text"
            value={formData.description}
            onChange={handleChange}
            placeholder="Descripción opcional"
            disabled={loading}
            data-testid="product-description-input"
          />
        </div>
      </div>

      <div className="form-row">
        <div className="form-group">
          <label htmlFor="price">Precio *</label>
          <input
            id="price"
            name="price"
            type="number"
            step="0.01"
            min="0"
            value={formData.price}
            onChange={handleChange}
            placeholder="0.00"
            required
            disabled={loading}
            data-testid="product-price-input"
          />
        </div>

        <div className="form-group">
          <label htmlFor="stock">Stock *</label>
          <input
            id="stock"
            name="stock"
            type="number"
            min="0"
            value={formData.stock}
            onChange={handleChange}
            placeholder="0"
            required
            disabled={loading}
            data-testid="product-stock-input"
          />
        </div>
      </div>

      <button
        type="submit"
        className="btn btn-primary"
        disabled={loading}
        data-testid="create-product-button"
      >
        {loading ? 'Creando...' : 'Crear Producto'}
      </button>
    </form>
  );
}
